version: "3.7"

services:

  flask:
    build: ./oauth
    container_name: ncnu_notify_oauth_flask
    # restart: always
    environment:
      - APP_NAME=FlaskApp
    volumes:
      - ./oauth:/home
    expose:
      - 8080


  nginx:
    build: ./nginx
    container_name: template_nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask